using System;
using TextEditor.Model;

namespace TextEditor.Exceptions
{
    /// <summary>
    /// Exception generated by segmentizer when it founds too big word to prevent algorithms from crash
    /// <see cref="Segmentizer"/>
    /// </summary>
    public class TooBigWordException : Exception
    {
        public TooBigWordException() : base("Too big word found") {}
    }
}
